### ISSUE TITLE
A problem about code

### ISSUE THREAD

**Issue by pangxiansen123** [nunziati/Lin-Kernighan-TSP-local-search#1]
In lin_kernighan_move() function, Whether there is an error about "for city_y1, _ in sorted([(c, partial_cost([(c, tour.pred(c)), (c,c)], [(c, x1[1]), (x1[0], tour.pred(c))])) for c in neighbours[x1[1]]], key=lambda z: z[1]):". 
Whether he should be "for city_y1, _ in sorted([(c, partial_cost([(c, tour.pred(c)), x1], [(c, x1[1]), (x1[0], tour.pred(c))])) for c in neighbours[x1[1]]], key=lambda z: z[1]):".

**Comment by nunziati** [comment]
You're right, in principle, but in practice that partial cost is only computed in order to sort the cities, and since the arc x1 is constant, its cost doesn't affect the sorting.
It can be replaced with any constant arc, in my case I decided to use the arc (c, c), with length always equal to 0, that is (maybe) faster to be computed.
Anyway, thank you for your follow up!
